"""add_ecommerce_models

Revision ID: e3875a431dee
Revises: fd971c67b65f
Create Date: 2025-03-31 14:16:22.734301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3875a431dee'
down_revision: Union[str, None] = 'fd971c67b65f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('technical_specs', 'pattern_repeat')
    op.drop_column('technical_specs', 'wear_layer')
    op.drop_column('technical_specs', 'removable')
    op.drop_column('technical_specs', 'coverage_area')
    op.drop_column('technical_specs', 'drying_time')
    op.drop_column('technical_specs', 'paint_finish')
    op.drop_column('technical_specs', 'washable')
    op.drop_column('technical_specs', 'voc_content')
    op.drop_column('users', 'permissions')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=20), server_default=sa.text("'customer'::character varying"), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('permissions', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('technical_specs', sa.Column('voc_content', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('technical_specs', sa.Column('washable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('technical_specs', sa.Column('paint_finish', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('technical_specs', sa.Column('drying_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('technical_specs', sa.Column('coverage_area', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('technical_specs', sa.Column('removable', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('technical_specs', sa.Column('wear_layer', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('technical_specs', sa.Column('pattern_repeat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
