# Update .github/workflows/deploy.yml
name: Deploy to roomflux.com

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          echo "Updating application code..."
          cd ~/roomflux/room_wall_visualizer/app/Room_Wall_Visualizer
          
          # Stash any local changes
          git stash
          
          # Pull latest changes
          git pull origin main
          
          echo "Restarting containers..."
          cd ~/roomflux
          docker-compose -f docker-compose-production.yaml restart
          
          echo "Deployment complete! Changes live on roomflux.com"
