name: Deploy to roomflux.com

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Fast zero-downtime deployment
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        timeout: 8m
        script: |
          echo "Starting fast deployment..."
          cd ~/roomflux
          
          # Pull latest changes
          git stash
          git pull origin main
          
          echo "Code updated via volume mount, restarting application..."
          # Since code is volume mounted, just restart the container
          docker-compose -f docker-compose-production.yaml restart app
          
          echo "Waiting for application to be ready..."
          # Wait for application to restart
          sleep 30
          
          # Health check
          for i in {1..20}; do
            if curl -f -s http://localhost/health > /dev/null 2>&1; then
              echo "Application is healthy and ready!"
              echo "Fast deployment completed successfully!"
              exit 0
            fi
            echo "Waiting for application... ($i/20)"
            sleep 10
          done
          
          echo "Health check failed, but deployment completed"
          echo "Please check application manually"
