name: Deploy to roomflux.com

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Zero-downtime deployment
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        timeout: 8m
        script: |
          echo "Starting deployment..."
          
          # Navigate to the git repository directory
          cd ~/roomflux/room_wall_visualizer/app/Room_Wall_Visualizer
          
          # Pull latest changes
          echo "Pulling latest changes..."
          git stash
          git pull origin main
          
          # Navigate back to docker-compose directory
          cd ~/roomflux
          
          echo "Code updated, restarting application..."
          # Restart the application container
          docker-compose -f docker-compose-production.yaml restart app
          
          echo "Waiting for application to be ready..."
          sleep 30
          
          # Health check
          HEALTHY=false
          for i in {1..15}; do
            if curl -f -s http://localhost/health > /dev/null 2>&1; then
              echo "Application is healthy and ready!"
              HEALTHY=true
              break
            fi
            echo "Waiting for application... ($i/15)"
            sleep 10
          done
          
          if [ "$HEALTHY" = "true" ]; then
            echo "✅ Deployment completed successfully!"
            echo "🚀 Application is live at roomflux.com"
          else
            echo "⚠️  Health check timeout - please verify manually"
          fi
          
          echo "Deployment process finished."
